In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\chand\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\chand\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"C:\Users\chand\Downloads\College\Infosys_Springboard\Dataset\fact_disease_surveillance.csv.xlsx")

In [5]:
df.shape

(13962, 18)

In [6]:
df.head()

,fact_id,date_id,state_id,disease_id,source_id,population_under_surveillance,total_reported_cases,active_cases,recovered_cases,deaths,urban_cases,rural_cases,hospitalized_cases,icu_admissions,case_fatality_rate,recovery_rate,public_health_risk_score,report_date_raw
0,1,1,1,1,6,46850798,2091,139,1889.0,63.0,1368,723,143,42.0,3.01,90.34,31.3,2022-01-01
1,2,1,1,2,6,46330962,2357,180,2101.0,76.0,1039,1318,505,81.0,3.22,89.14,32.1,2022-01-01
2,3,1,1,3,2,49588439,2936,427,2430.0,79.0,1941,995,716,195.0,2.69,82.77,32.3,2022-01-01
3,4,1,1,4,1,47346875,335,21,306.0,8.0,166,169,81,10.0,2.39,91.34,10.0,2022-01-01
4,5,1,1,5,5,52543820,310,30,NaN,2.0,195,115,42,10.0,0.65,89.68,2.9,2022-01-01

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13962 entries, 0 to 13961
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   fact_id                        13962 non-null  int64
 1   date_id                        13962 non-null  int64
 2   state_id                       13962 non-null  int64
 3   disease_id                     13962 non-null  int64
 4   source_id                      13962 non-null  int64
 5   population_under_surveillance  13962 non-null  int64
 6   total_reported_cases           13962 non-null  int64
 7   active_cases                   13962 non-null  int64
 8   recovered_cases                13543 non-null  float64
 9   deaths                         13540 non-null  float64
 10  urban_cases                    13962 non-null  int64
 11  rural_cases                    13962 non-null  int64
 12  hospitalized_cases             13499 non-null  object
 13  icu_admissions                 13545 non-null  float64
 14  case_fatality_rate             13543 non-null  float64
 15  recovery_rate                  13962 non-null  float64
 16  public_health_risk_score       13962 non-null  float64
 17  report_date_raw                13962 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(10), object(1)
memory usage: 1.9+ MB

In [9]:
df.describe()

,fact_id,date_id,state_id,disease_id,source_id,population_under_surveillance,total_reported_cases,active_cases,recovered_cases,deaths,urban_cases,rural_cases,icu_admissions,case_fatality_rate,recovery_rate,public_health_risk_score,report_date_raw
count,13962.000000,13962.00000,13962.000000,13962.000000,13962.000000,1.396200e+04,13962.000000,13962.000000,13543.000000,13540.000000,13962.000000,13962.000000,13545.000000,13543.000000,13962.000000,13962.000000,13962
mean,6909.537172,18.49248,16.494055,6.496347,3.500000,4.019925e+07,1090.822089,134.000501,933.506387,19.427548,602.419711,488.402378,27.879365,1.889609,85.035900,16.273793,2023-06-11 14:11:17.610657536
min,1.000000,1.00000,1.000000,1.000000,1.000000,2.550530e+05,0.000000,-1555.000000,0.000000,-233.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2022-01-01 00:00:00
25%,3457.250000,10.00000,8.000000,3.000000,2.000000,3.002225e+06,72.000000,8.000000,62.000000,1.000000,37.000000,33.000000,1.000000,0.250000,79.550000,9.200000,2022-09-01 00:00:00
50%,6913.500000,19.00000,16.000000,6.000000,4.000000,2.921228e+07,542.000000,49.000000,465.000000,7.000000,288.500000,231.000000,10.000000,1.370000,85.210000,14.800000,2023-06-01 00:00:00
75%,10360.750000,27.00000,24.000000,10.000000,5.000000,6.375425e+07,1402.750000,156.000000,1192.000000,23.000000,755.000000,620.000000,33.000000,2.340000,90.860000,21.300000,2024-03-01 00:00:00
max,13824.000000,36.00000,32.000000,12.000000,6.000000,2.314685e+08,28799.000000,4699.000000,24827.000000,788.000000,16263.000000,13417.000000,1002.000000,139.000000,139.800000,76.800000,2024-12-01 00:00:00
std,3988.904830,10.38385,9.234585,3.454103,1.710359,4.568982e+07,1676.238198,244.854600,1436.873745,35.920238,953.712803,781.562455,52.383480,7.882401,8.175208,10.132337,NaN

In [11]:
df.duplicated().sum()

np.int64(138)

In [12]:
df[df.duplicated()].head()

,fact_id,date_id,state_id,disease_id,source_id,population_under_surveillance,total_reported_cases,active_cases,recovered_cases,deaths,urban_cases,rural_cases,hospitalized_cases,icu_admissions,case_fatality_rate,recovery_rate,public_health_risk_score,report_date_raw
13824,4289,12,6,5,4,1559137,11,2,9.0,0.0,5,6,1,0.0,0.00,81.82,3.1,2022-12-01
13825,8197,22,12,1,1,31707356,1499,338,1129.0,32.0,1073,426,NaN,19.0,2.13,75.32,28.2,2023-10-01
13826,7559,20,22,11,3,618895,21,2,19.0,0.0,11,10,3,0.0,0.00,90.48,11.0,2023-01-08
13827,7199,19,24,11,4,38704268,1045,20,1009.0,NaN,651,394,200,30.0,1.53,96.56,22.3,2023-07-01
13828,4640,13,3,8,2,33426103,471,19,446.0,6.0,209,262,89,14.0,1.27,94.69,11.4,2023-01-01

In [13]:
df.isnull().sum()

fact_id                            0
date_id                            0
state_id                           0
disease_id                         0
source_id                          0
population_under_surveillance      0
total_reported_cases               0
active_cases                       0
recovered_cases                  419
deaths                           422
urban_cases                        0
rural_cases                        0
hospitalized_cases               463
icu_admissions                   417
case_fatality_rate               419
recovery_rate                      0
public_health_risk_score           0
report_date_raw                    0
dtype: int64

In [14]:
df["hospitalized_cases"].unique()

array([143, 505, 716, ..., 666, 1135, 1152], shape=(1088,), dtype=object)

In [15]:
df[df["active_cases"]<0]

,fact_id,date_id,state_id,disease_id,source_id,population_under_surveillance,total_reported_cases,active_cases,recovered_cases,deaths,urban_cases,rural_cases,hospitalized_cases,icu_admissions,case_fatality_rate,recovery_rate,public_health_risk_score,report_date_raw
73,74,1,7,2,2,70386729,2165,-385,1713.0,NaN,1379,786,144,19.0,3.09,79.12,27.7,2022-01-01
173,174,1,15,6,2,2899197,61,-14,46.0,-1.0,33,28,3,0.0,1.64,75.41,13.8,2022-01-01
356,357,1,30,9,2,12234425,375,-74,293.0,-8.0,133,242,74,10.0,2.13,78.13,18.0,2022-01-01
400,401,2,2,5,1,1526687,11,-2,9.0,0.0,7,4,1,0.0,0.00,81.82,4.5,2022-02-01
640,641,2,22,5,5,699530,7,-2,5.0,NaN,4,3,1,0.0,0.00,71.43,0.0,2022-02-01
891,892,3,11,4,3,62101919,1379,-295,1059.0,-25.0,709,670,299,27.0,1.81,76.79,19.0,2022-03-01
1112,1113,3,29,9,2,32897365,1133,-87,1011.0,-35.0,725,408,187,44.0,3.09,89.23,22.6,2022-03-01
1239,1240,4,8,4,5,27164938,607,-55,532.0,-20.0,382,225,92,14.0,3.29,87.64,24.6,2022-04-01
1348,1349,4,17,5,3,1133131,25,-2,23.0,0.0,18,7,4,0.0,0.00,92.00,5.6,2022-04-01
1432,1433,4,24,5,1,39149546,816,-88,702.0,-26.0,492,324,177,21.0,3.19,86.03,20.4,2022-04-01
1568,1569,5,3,9,5,35139522,1514,-154,1349.0,-11.0,1037,477,315,60.0,0.73,89.10,22.1,2022-05-01
1613,1614,5,7,6,1,66322042,1119,-270,844.0,-5.0,581,538,121,7.0,0.45,75.42,12.4,2022-05-01
2081,2082,6,14,6,2,107919864,1700,-312,1377.0,-11.0,989,711,89,11.0,0.65,81.00,13.4,2022-06-01
2609,2610,7,26,6,4,226545662,4472,-262,4071.0,-139.0,2974,1498,1080,NaN,3.11,91.03,22.0,2022-07-01
2900,2901,8,18,9,4,2180464,17,-3,14.0,0.0,10,7,1,0.0,0.00,82.35,8.2,2022-08-01
2904,2905,8,19,1,1,43850332,1291,-206,1042.0,-43.0,886,405,276,47.0,3.33,80.71,20.7,2022-08-01
3556,3557,10,9,5,1,6939116,211,-10,200.0,NaN,84,127,43,6.0,0.47,94.79,16.1,2022-10-01
3683,3684,10,19,12,1,41370035,1059,-53,974.0,-32.0,759,300,65,6.0,3.02,91.97,25.3,2022-10-01
3743,3744,10,24,12,1,34992711,822,-12,795.0,-15.0,541,281,202,39.0,NaN,96.72,13.3,2022-10-01
3758,3759,10,26,3,6,212056197,2084,-133,1901.0,-50.0,1217,867,226,41.0,2.40,91.22,8.3,2022-10-01
3765,3766,10,26,10,5,228156893,1871,-157,1674.0,-40.0,708,1163,281,42.0,2.14,89.47,12.4,2022-10-01
4092,4093,11,22,1,2,646757,14,-1,13.0,0.0,5,9,2,0.0,0.00,92.86,6.7,2022-11-01
4395,4396,12,15,4,4,3009497,36,-3,33.0,0.0,16,20,7,1.0,0.00,91.67,10.8,2022-12-01
4571,4572,12,29,12,6,31187726,396,-14,381.0,-1.0,148,248,56,14.0,0.25,96.21,10.2,2022-12-01
4587,4588,12,31,4,3,267790,5,-1,4.0,0.0,2,3,1,0.0,0.00,80.00,0.9,2022-12-01
4655,4656,13,4,12,2,110419223,3627,-295,3253.0,-79.0,1493,2134,689,90.0,2.18,89.69,20.8,2023-01-01
4835,4836,13,19,12,3,45505368,638,-124,504.0,-10.0,307,331,34,5.0,1.57,79.00,7.5,2023-01-01
5070,5071,14,7,7,2,69425030,495,-102,381.0,-12.0,213,282,47,5.0,2.42,76.97,9.1,2023-02-01
5605,5606,15,20,2,6,26922333,333,-26,302.0,-5.0,144,189,61,14.0,1.50,90.69,12.4,2023-03-01
5676,5677,15,26,1,2,201247859,2302,-60,2185.0,-57.0,905,1397,NaN,30.0,2.48,94.92,14.0,2023-03-01
6213,6214,17,6,10,3,1395053,77,-7,69.0,-1.0,33,44,18,2.0,1.30,89.61,29.5,2023-05-01
6219,6220,17,7,4,1,67559101,534,-26,499.0,-9.0,214,320,66,3.0,1.69,93.45,5.4,2023-05-01
6513,6514,17,31,10,2,298698,8,-2,6.0,0.0,4,4,1,0.0,0.00,75.00,2.6,2023-05-01
6587,6588,18,5,12,4,29016931,929,-87,838.0,-4.0,355,574,100,12.0,0.43,90.20,16.3,2023-06-01
7595,7596,20,25,12,3,3897733,58,-9,49.0,0.0,28,30,3,0.0,0.00,84.48,8.9,2023-08-01
7918,7919,21,20,11,4,26600496,566,-91,466.0,-9.0,339,227,91,5.0,1.59,82.33,18.0,2023-09-01
8096,8097,22,3,9,6,33957476,401,-74,320.0,-7.0,259,142,89,19.0,1.75,79.80,15.4,2023-10-01
8158,8159,22,8,11,6,27487232,938,-127,790.0,-21.0,512,426,91,9.0,2.24,84.22,20.4,2023-10-01
8336,8337,22,23,9,3,68265067,1896,-299,1537.0,-60.0,1333,563,345,62.0,3.16,81.07,23.6,2023-10-01
8354,8355,22,25,3,4,3486865,90,-4,83.0,-3.0,63,27,14,1.0,3.33,92.22,22.3,2023-10-01
8721,8722,23,23,10,5,77213938,1085,-65,999.0,-21.0,800,285,178,21.0,1.94,92.07,9.6,2023-11-01
8860,8861,24,3,5,6,31348419,391,-36,351.0,-4.0,286,105,82,12.0,1.02,89.77,5.1,2023-12-01
9235,9236,25,2,8,1,1531263,25,-2,NaN,0.0,8,17,1,0.0,0.00,92.00,4.7,2024-01-01
9329,9330,25,10,6,3,33405786,452,-49,400.0,-3.0,271,181,78,6.0,0.66,88.50,5.9,2024-01-01
9344,9345,25,11,9,1,67090292,2011,-425,1521.0,-65.0,1268,743,236,32.0,3.23,75.63,29.4,2024-01-01
10327,10328,27,29,8,6,29767632,391,-53,337.0,-1.0,199,192,77,NaN,0.26,86.19,1.8,2024-03-01
10588,10589,28,19,5,3,45048094,521,-69,448.0,-4.0,259,262,70,12.0,0.77,85.99,3.9,2024-04-01
10686,10687,28,27,7,3,18556132,395,-59,326.0,-10.0,198,197,45,6.0,2.53,82.53,18.4,2024-04-01
10750,10751,28,32,11,5,1408430,49,-2,46.0,-1.0,35,14,10,2.0,2.04,93.88,25.4,2024-04-01
11569,11570,31,5,2,1,28489248,409,-52,348.0,-9.0,283,126,89,24.0,2.20,85.09,16.8,2024-07-01
11723,11724,31,17,12,6,1171419,44,-10,33.0,-1.0,21,23,2,0.0,2.27,75.00,28.9,2024-07-01
12052,12053,32,13,5,5,83212707,7577,-1555,5789.0,-233.0,3960,3617,1550,108.0,3.08,76.40,52.3,2024-08-01
12175,12176,32,23,8,3,66684418,1790,-109,1619.0,-62.0,883,907,328,62.0,3.46,90.45,18.8,2024-08-01
12679,12680,34,1,8,1,47131850,1750,-98,1644.0,-8.0,1157,593,353,23.0,0.46,93.94,19.5,2024-10-01
13667,13668,36,19,12,4,42536354,2355,-338,1986.0,-31.0,1004,1351,362,89.0,1.32,84.33,28.1,2024-12-01

In [16]:
df[df["deaths"]<0]

,fact_id,date_id,state_id,disease_id,source_id,population_under_surveillance,total_reported_cases,active_cases,recovered_cases,deaths,urban_cases,rural_cases,hospitalized_cases,icu_admissions,case_fatality_rate,recovery_rate,public_health_risk_score,report_date_raw
173,174,1,15,6,2,2899197,61,-14,46.0,-1.0,33,28,3,0.0,1.64,75.41,13.8,2022-01-01
356,357,1,30,9,2,12234425,375,-74,293.0,-8.0,133,242,74,10.0,2.13,78.13,18.0,2022-01-01
891,892,3,11,4,3,62101919,1379,-295,1059.0,-25.0,709,670,299,27.0,1.81,76.79,19.0,2022-03-01
1112,1113,3,29,9,2,32897365,1133,-87,1011.0,-35.0,725,408,187,44.0,3.09,89.23,22.6,2022-03-01
1239,1240,4,8,4,5,27164938,607,-55,532.0,-20.0,382,225,92,14.0,3.29,87.64,24.6,2022-04-01
1432,1433,4,24,5,1,39149546,816,-88,702.0,-26.0,492,324,177,21.0,3.19,86.03,20.4,2022-04-01
1568,1569,5,3,9,5,35139522,1514,-154,1349.0,-11.0,1037,477,315,60.0,0.73,89.10,22.1,2022-05-01
1613,1614,5,7,6,1,66322042,1119,-270,844.0,-5.0,581,538,121,7.0,0.45,75.42,12.4,2022-05-01
2081,2082,6,14,6,2,107919864,1700,-312,1377.0,-11.0,989,711,89,11.0,0.65,81.00,13.4,2022-06-01
2609,2610,7,26,6,4,226545662,4472,-262,4071.0,-139.0,2974,1498,1080,NaN,3.11,91.03,22.0,2022-07-01
2904,2905,8,19,1,1,43850332,1291,-206,1042.0,-43.0,886,405,276,47.0,3.33,80.71,20.7,2022-08-01
3683,3684,10,19,12,1,41370035,1059,-53,974.0,-32.0,759,300,65,6.0,3.02,91.97,25.3,2022-10-01
3743,3744,10,24,12,1,34992711,822,-12,795.0,-15.0,541,281,202,39.0,NaN,96.72,13.3,2022-10-01
3758,3759,10,26,3,6,212056197,2084,-133,1901.0,-50.0,1217,867,226,41.0,2.40,91.22,8.3,2022-10-01
3765,3766,10,26,10,5,228156893,1871,-157,1674.0,-40.0,708,1163,281,42.0,2.14,89.47,12.4,2022-10-01
4571,4572,12,29,12,6,31187726,396,-14,381.0,-1.0,148,248,56,14.0,0.25,96.21,10.2,2022-12-01
4655,4656,13,4,12,2,110419223,3627,-295,3253.0,-79.0,1493,2134,689,90.0,2.18,89.69,20.8,2023-01-01
4835,4836,13,19,12,3,45505368,638,-124,504.0,-10.0,307,331,34,5.0,1.57,79.00,7.5,2023-01-01
5070,5071,14,7,7,2,69425030,495,-102,381.0,-12.0,213,282,47,5.0,2.42,76.97,9.1,2023-02-01
5605,5606,15,20,2,6,26922333,333,-26,302.0,-5.0,144,189,61,14.0,1.50,90.69,12.4,2023-03-01
5676,5677,15,26,1,2,201247859,2302,-60,2185.0,-57.0,905,1397,NaN,30.0,2.48,94.92,14.0,2023-03-01
6213,6214,17,6,10,3,1395053,77,-7,69.0,-1.0,33,44,18,2.0,1.30,89.61,29.5,2023-05-01
6219,6220,17,7,4,1,67559101,534,-26,499.0,-9.0,214,320,66,3.0,1.69,93.45,5.4,2023-05-01
6587,6588,18,5,12,4,29016931,929,-87,838.0,-4.0,355,574,100,12.0,0.43,90.20,16.3,2023-06-01
7918,7919,21,20,11,4,26600496,566,-91,466.0,-9.0,339,227,91,5.0,1.59,82.33,18.0,2023-09-01
8096,8097,22,3,9,6,33957476,401,-74,320.0,-7.0,259,142,89,19.0,1.75,79.80,15.4,2023-10-01
8158,8159,22,8,11,6,27487232,938,-127,790.0,-21.0,512,426,91,9.0,2.24,84.22,20.4,2023-10-01
8336,8337,22,23,9,3,68265067,1896,-299,1537.0,-60.0,1333,563,345,62.0,3.16,81.07,23.6,2023-10-01
8354,8355,22,25,3,4,3486865,90,-4,83.0,-3.0,63,27,14,1.0,3.33,92.22,22.3,2023-10-01
8721,8722,23,23,10,5,77213938,1085,-65,999.0,-21.0,800,285,178,21.0,1.94,92.07,9.6,2023-11-01
8860,8861,24,3,5,6,31348419,391,-36,351.0,-4.0,286,105,82,12.0,1.02,89.77,5.1,2023-12-01
9329,9330,25,10,6,3,33405786,452,-49,400.0,-3.0,271,181,78,6.0,0.66,88.50,5.9,2024-01-01
9344,9345,25,11,9,1,67090292,2011,-425,1521.0,-65.0,1268,743,236,32.0,3.23,75.63,29.4,2024-01-01
10327,10328,27,29,8,6,29767632,391,-53,337.0,-1.0,199,192,77,NaN,0.26,86.19,1.8,2024-03-01
10588,10589,28,19,5,3,45048094,521,-69,448.0,-4.0,259,262,70,12.0,0.77,85.99,3.9,2024-04-01
10686,10687,28,27,7,3,18556132,395,-59,326.0,-10.0,198,197,45,6.0,2.53,82.53,18.4,2024-04-01
10750,10751,28,32,11,5,1408430,49,-2,46.0,-1.0,35,14,10,2.0,2.04,93.88,25.4,2024-04-01
11569,11570,31,5,2,1,28489248,409,-52,348.0,-9.0,283,126,89,24.0,2.20,85.09,16.8,2024-07-01
11723,11724,31,17,12,6,1171419,44,-10,33.0,-1.0,21,23,2,0.0,2.27,75.00,28.9,2024-07-01
12052,12053,32,13,5,5,83212707,7577,-1555,5789.0,-233.0,3960,3617,1550,108.0,3.08,76.40,52.3,2024-08-01
12175,12176,32,23,8,3,66684418,1790,-109,1619.0,-62.0,883,907,328,62.0,3.46,90.45,18.8,2024-08-01
12679,12680,34,1,8,1,47131850,1750,-98,1644.0,-8.0,1157,593,353,23.0,0.46,93.94,19.5,2024-10-01
13667,13668,36,19,12,4,42536354,2355,-338,1986.0,-31.0,1004,1351,362,89.0,1.32,84.33,28.1,2024-12-01

In [17]:
df[df["recovered_cases"]<0]

Empty DataFrame
Columns: [fact_id, date_id, state_id, disease_id, source_id, population_under_surveillance, total_reported_cases, active_cases, recovered_cases, deaths, urban_cases, rural_cases, hospitalized_cases, icu_admissions, case_fatality_rate, recovery_rate, public_health_risk_score, report_date_raw]
Index: []

In [18]:
df[df["hospitalized_cases"].astype(str).str.contains("-")]

,fact_id,date_id,state_id,disease_id,source_id,population_under_surveillance,total_reported_cases,active_cases,recovered_cases,deaths,urban_cases,rural_cases,hospitalized_cases,icu_admissions,case_fatality_rate,recovery_rate,public_health_risk_score,report_date_raw
221,222,1,19,6,3,40246656,265,29,229.0,7.0,193,72,-,9.0,2.64,86.42,12.3,2022-01-01
452,453,2,6,9,3,1434316,24,6,18.0,0.0,11,13,-,0.0,0.00,75.00,9.8,2022-02-01
2033,2034,6,10,6,4,36606499,580,42,530.0,8.0,373,207,-,10.0,1.38,91.38,9.3,2022-06-01
2378,2379,7,7,3,2,60815350,976,28,931.0,17.0,725,251,-,48.0,1.74,95.39,14.1,2022-07-01
4577,4578,12,30,6,1,11594083,77,18,59.0,0.0,49,28,-,5.0,0.00,76.62,6.7,2022-12-01
4637,4638,13,3,6,1,35302988,498,57,440.0,1.0,210,288,-,25.0,0.20,88.35,3.0,2023-01-01
5843,5844,16,7,12,6,64598136,1700,215,1472.0,13.0,698,1002,-,56.0,0.76,86.59,14.0,2023-04-01
6173,6174,17,3,6,4,33128078,421,63,346.0,12.0,262,159,-,10.0,2.85,82.19,10.1,2023-05-01
7596,7597,20,26,1,1,208879338,6869,1505,5316.0,48.0,4702,2167,-,185.0,0.70,77.39,16.0,2023-08-01
8855,8856,24,2,12,6,1522876,42,1,40.0,1.0,21,21,-,1.0,2.38,95.24,19.3,2023-12-01
11290,11291,30,13,11,2,82651098,781,54,724.0,3.0,349,432,-,20.0,0.38,92.70,7.3,2024-01-06
11551,11552,31,3,8,1,34423792,549,111,434.0,4.0,240,309,-,8.0,0.73,79.05,6.9,2024-07-01
12334,12335,33,4,11,4,124613835,6066,1447,4554.0,65.0,2282,3784,-,111.0,1.07,75.07,28.7,2024-09-01
12625,12626,33,29,2,6,30833079,1160,207,925.0,28.0,751,409,-,52.0,2.41,79.74,22.5,2024-09-01
12958,12959,34,24,11,5,35040056,425,89,331.0,5.0,218,207,-,4.0,1.18,77.88,4.9,2024-10-01
13402,13403,35,29,11,6,32560657,721,66,638.0,17.0,497,224,-,7.0,2.36,88.49,15.5,2024-11-01
13615,13616,36,15,8,6,3059197,18,2,16.0,0.0,10,8,-,0.0,0.00,88.89,3.0,2024-12-01

In [19]:
(df["active_cases"] < 0).sum()

np.int64(55)

In [21]:
(df["deaths"]<0).sum()

np.int64(43)

In [22]:
(df["total_reported_cases"] < 0).sum()

np.int64(0)

In [23]:
(df["urban_cases"] < 0).sum()

np.int64(0)

In [24]:
(df["rural_cases"] < 0).sum()

np.int64(0)

In [25]:
(df["icu_admissions"] < 0).sum()

np.int64(0)

In [26]:
df["difference"] = (
    df["total_reported_cases"]
    - (
        df["active_cases"]
        + df["recovered_cases"]
        + df["deaths"]
    )
)

df["difference"].describe()

count    13137.000000
mean         1.161605
std         37.644245
min        -10.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       3576.000000
Name: difference, dtype: float64

In [27]:
df["difference"].value_counts().head(20)

difference
 0.0      13080
 4.0          3
 6.0          3
 30.0         2
-2.0          2
 228.0        2
 2.0          2
 244.0        1
 640.0        1
 150.0        1
 550.0        1
 330.0        1
 646.0        1
 802.0        1
 498.0        1
 170.0        1
 54.0         1
 164.0        1
 366.0        1
 394.0        1
Name: count, dtype: int64

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df["hospitalized_cases"]=df["hospitalized_cases"].replace("-",np.nan)

In [33]:
df["hospitalized_cases"]=pd.to_numeric(
    df["hospitalized_cases"],
    errors="coerce"
)

In [35]:
df["hospitalized_cases"].dtype

dtype('float64')

In [36]:
df.loc[df["active_cases"]<0, "active_cases"]=np.nan

In [38]:
df.loc[df["deaths"]<0,"deaths"]=np.nan

In [39]:
(df["active_cases"]<0).sum()

np.int64(0)

In [40]:
(df["deaths"]<0).sum()

np.int64(0)

In [41]:
df.isnull().sum()

fact_id                            0
date_id                            0
state_id                           0
disease_id                         0
source_id                          0
population_under_surveillance      0
total_reported_cases               0
active_cases                      55
recovered_cases                  414
deaths                           457
urban_cases                        0
rural_cases                        0
hospitalized_cases               548
icu_admissions                   414
case_fatality_rate               413
recovery_rate                      0
public_health_risk_score           0
report_date_raw                    0
difference                       812
dtype: int64

In [42]:
df.drop(columns="difference",inplace=True)

In [43]:
df.columns

Index(['fact_id', 'date_id', 'state_id', 'disease_id', 'source_id',
       'population_under_surveillance', 'total_reported_cases', 'active_cases',
       'recovered_cases', 'deaths', 'urban_cases', 'rural_cases',
       'hospitalized_cases', 'icu_admissions', 'case_fatality_rate',
       'recovery_rate', 'public_health_risk_score', 'report_date_raw'],
      dtype='object')

In [44]:
df[
    [
        "active_cases",
        "recovered_cases",
        "deaths",
        "hospitalized_cases",
        "icu_admissions",
        "case_fatality_rate"
    ]
].describe()

,active_cases,recovered_cases,deaths,hospitalized_cases,icu_admissions,case_fatality_rate
count,13769.000000,13410.000000,13367.000000,13276.000000,13410.000000,13411.000000
mean,134.990994,934.140268,19.589287,163.579542,27.901342,1.884677
std,244.077300,1438.501172,35.867304,271.859678,52.461460,7.854207
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.000000,62.000000,1.000000,10.000000,1.000000,0.250000
50%,49.000000,466.000000,7.000000,70.000000,10.000000,1.370000
75%,156.000000,1193.000000,23.000000,200.000000,33.000000,2.340000
max,4699.000000,24827.000000,788.000000,4235.000000,1002.000000,139.000000

In [45]:
df[
    [
        "active_cases",
        "recovered_cases",
        "deaths",
        "hospitalized_cases",
        "icu_admissions",
        "case_fatality_rate"
    ]
].skew()

active_cases           5.129434
recovered_cases        4.205719
deaths                 5.264007
hospitalized_cases     4.470307
icu_admissions         5.675107
case_fatality_rate    15.198878
dtype: float64

In [46]:
cols = [
    "active_cases",
    "recovered_cases",
    "deaths",
    "hospitalized_cases",
    "icu_admissions",
    "case_fatality_rate"
]

for col in cols:
    df[col] = df[col].fillna(df[col].median())

In [47]:
df.isnull().sum()

fact_id                          0
date_id                          0
state_id                         0
disease_id                       0
source_id                        0
population_under_surveillance    0
total_reported_cases             0
active_cases                     0
recovered_cases                  0
deaths                           0
urban_cases                      0
rural_cases                      0
hospitalized_cases               0
icu_admissions                   0
case_fatality_rate               0
recovery_rate                    0
public_health_risk_score         0
report_date_raw                  0
dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13824 entries, 0 to 13823
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   fact_id                        13824 non-null  int64
 1   date_id                        13824 non-null  int64
 2   state_id                       13824 non-null  int64
 3   disease_id                     13824 non-null  int64
 4   source_id                      13824 non-null  int64
 5   population_under_surveillance  13824 non-null  int64
 6   total_reported_cases           13824 non-null  int64
 7   active_cases                   13824 non-null  float64
 8   recovered_cases                13824 non-null  float64
 9   deaths                         13824 non-null  float64
 10  urban_cases                    13824 non-null  int64
 11  rural_cases                    13824 non-null  int64
 12  hospitalized_cases             13824 non-null  float64
 13  icu_admissions                 13824 non-null  float64
 14  case_fatality_rate             13824 non-null  float64
 15  recovery_rate                  13824 non-null  float64
 16  public_health_risk_score       13824 non-null  float64
 17  report_date_raw                13824 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(8), int64(9)
memory usage: 2.0 MB

In [49]:
df.to_excel("fact_disease_surveillance_cleaned.xlsx", index=False)