In [1]:
import pandas as pd

In [6]:
df=pd.read_csv(r"C:\Users\attil\Downloads\fact_environmental.csv")
df.head()

,fact_id,date_id,state_id,aqi,rainfall_mm,temperature_c,water_quality_index,sanitation_coverage_pct,healthcare_accessibility_score,mosquito_breeding_index,zoonotic_disease_incidence,geographic_risk_score,environmental_risk_score,case_rate_per_100k,hotspot_flag
0,1,1,1,147.3,10.4,18.4,70.5,56.9,88.5,45.7,15.0,45.0,40.8,21.3,NO
1,2,1,2,106.4,57.2,16.9,94.2,96.1,52.8,21.1,15.7,21.3,22.9,80.9,NO
2,3,1,3,142.2,7.2,16.4,54.5,93.1,94.5,18.9,29.8,33.2,41.4,122.5,No
3,4,1,4,129.2,26.8,10.7,78.4,NaN,89.5,48.9,21.2,31.9,33.7,164.0,yes
4,5,1,5,120.8,44.3,20.4,60.8,70.5,84.9,39.7,11.8,39.4,35.3,117.0,False

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   fact_id                         1169 non-null   int64
 1   date_id                         1169 non-null   int64
 2   state_id                        1169 non-null   int64
 3   aqi                             1123 non-null   float64
 4   rainfall_mm                     1169 non-null   float64
 5   temperature_c                   1169 non-null   float64
 6   water_quality_index             1121 non-null   float64
 7   sanitation_coverage_pct         1123 non-null   float64
 8   healthcare_accessibility_score  1169 non-null   float64
 9   mosquito_breeding_index         1169 non-null   float64
 10  zoonotic_disease_incidence      1169 non-null   float64
 11  geographic_risk_score           1169 non-null   float64
 12  environmental_risk_score        1169 non-null   float64
 13  case_rate_per_100k              1169 non-null   float64
 14  hotspot_flag                    1169 non-null   object
dtypes: float64(11), int64(3), object(1)
memory usage: 137.1+ KB

In [8]:
df.describe()

,fact_id,date_id,state_id,aqi,rainfall_mm,temperature_c,water_quality_index,sanitation_coverage_pct,healthcare_accessibility_score,mosquito_breeding_index,zoonotic_disease_incidence,geographic_risk_score,environmental_risk_score,case_rate_per_100k
count,1169.000000,1169.000000,1169.000000,1123.000000,1169.000000,1169.000000,1121.000000,1123.000000,1169.000000,1169.000000,1169.000000,1169.000000,1169.000000,1169.000000
mean,575.856287,18.478186,16.554320,131.891838,110.219504,26.947648,67.221409,76.729386,67.272370,53.607613,18.328486,36.806074,38.492301,130.304021
std,331.415574,10.352424,9.233408,70.197123,121.620212,9.745374,15.700092,12.521103,15.865743,37.324479,8.469948,6.751675,12.940492,70.294006
min,1.000000,1.000000,1.000000,54.000000,0.200000,8.100000,40.100000,55.100000,40.000000,7.000000,0.000000,19.800000,11.700000,5.400000
25%,289.000000,10.000000,9.000000,91.750000,23.200000,18.400000,53.900000,65.800000,53.400000,27.000000,12.500000,31.900000,28.700000,69.800000
50%,577.000000,19.000000,17.000000,121.800000,44.800000,28.400000,67.100000,76.600000,66.600000,43.900000,17.600000,36.900000,36.700000,132.300000
75%,861.000000,27.000000,25.000000,154.900000,208.500000,35.300000,81.000000,87.500000,80.900000,61.900000,23.100000,41.900000,45.500000,191.100000
max,1152.000000,36.000000,32.000000,890.246762,399.900000,42.000000,95.000000,97.900000,94.900000,161.700000,50.800000,54.000000,75.100000,249.900000

In [9]:
df.duplicated().sum()

np.int64(17)

In [10]:
df["aqi"]=df["aqi"].fillna(df["aqi"].median())

In [12]:
df["water_quality_index"]=df["water_quality_index"].fillna(df["water_quality_index"].median())

In [13]:
df["sanitation_coverage_pct"]=df["sanitation_coverage_pct"].fillna(df["sanitation_coverage_pct"].median())

In [15]:
df["hotspot_flag"]=df["hotspot_flag"].astype(str).str.lower().str.strip()
df["hotspot_flag"]=df["hotspot_flag"].replace({'yes':'true','1':'true','y':'true','no':'false','0':'false','n':'false'})
df["hotspot_flag"].value_counts()

hotspot_flag
false    669
true     500
Name: count, dtype: int64

In [16]:
df.duplicated().sum()

np.int64(17)

In [18]:
df=df.drop_duplicates()

In [20]:
df.to_csv(r"C:\Users\attil\Downloads\fact_environmental_cleaned.csv",index=False)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1152 entries, 0 to 1151
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   fact_id                         1152 non-null   int64
 1   date_id                         1152 non-null   int64
 2   state_id                        1152 non-null   int64
 3   aqi                             1152 non-null   float64
 4   rainfall_mm                     1152 non-null   float64
 5   temperature_c                   1152 non-null   float64
 6   water_quality_index             1152 non-null   float64
 7   sanitation_coverage_pct         1152 non-null   float64
 8   healthcare_accessibility_score  1152 non-null   float64
 9   mosquito_breeding_index         1152 non-null   float64
 10  zoonotic_disease_incidence      1152 non-null   float64
 11  geographic_risk_score           1152 non-null   float64
 12  environmental_risk_score        1152 non-null   float64
 13  case_rate_per_100k              1152 non-null   float64
 14  hotspot_flag                    1152 non-null   object
dtypes: float64(11), int64(3), object(1)
memory usage: 144.0+ KB

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.isna().sum()

fact_id                           0
date_id                           0
state_id                          0
aqi                               0
rainfall_mm                       0
temperature_c                     0
water_quality_index               0
sanitation_coverage_pct           0
healthcare_accessibility_score    0
mosquito_breeding_index           0
zoonotic_disease_incidence        0
geographic_risk_score             0
environmental_risk_score          0
case_rate_per_100k                0
hotspot_flag                      0
dtype: int64